apiVersion: v1
kind: Service
metadata:
  name: hstest
  labels:
    run: hstest
spec:
  type: NodePort
  ports:
  - port: 18080
    targetPort: 18080
    protocol: TCP
    name: http
  selector:
    run: hstest
